/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    ABadge: typeof import('ant-design-vue/es')['Badge']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    AEmpty: typeof import('ant-design-vue/es')['Empty']
    AFloatButton: typeof import('ant-design-vue/es')['FloatButton']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AImage: typeof import('ant-design-vue/es')['Image']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    AInputSearch: typeof import('ant-design-vue/es')['InputSearch']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    GIcon: typeof import('./src/components/GIcon/GIcon.vue')['default']
    GLoading: typeof import('./src/components/GLoading/GLoading.vue')['default']
    GPage: typeof import('./src/components/GPage/GPage.vue')['default']
    GProgressBar: typeof import('./src/components/GProgressBar/GProgressBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const AAvatar: typeof import('ant-design-vue/es')['Avatar']
  const ABadge: typeof import('ant-design-vue/es')['Badge']
  const AButton: typeof import('ant-design-vue/es')['Button']
  const ACard: typeof import('ant-design-vue/es')['Card']
  const ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
  const AEmpty: typeof import('ant-design-vue/es')['Empty']
  const AFloatButton: typeof import('ant-design-vue/es')['FloatButton']
  const AForm: typeof import('ant-design-vue/es')['Form']
  const AFormItem: typeof import('ant-design-vue/es')['FormItem']
  const AImage: typeof import('ant-design-vue/es')['Image']
  const AInput: typeof import('ant-design-vue/es')['Input']
  const AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
  const AInputSearch: typeof import('ant-design-vue/es')['InputSearch']
  const AMenu: typeof import('ant-design-vue/es')['Menu']
  const ASelect: typeof import('ant-design-vue/es')['Select']
  const ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
  const ATag: typeof import('ant-design-vue/es')['Tag']
  const ATextarea: typeof import('ant-design-vue/es')['Textarea']
  const ATooltip: typeof import('ant-design-vue/es')['Tooltip']
  const GIcon: typeof import('./src/components/GIcon/GIcon.vue')['default']
  const GLoading: typeof import('./src/components/GLoading/GLoading.vue')['default']
  const GPage: typeof import('./src/components/GPage/GPage.vue')['default']
  const GProgressBar: typeof import('./src/components/GProgressBar/GProgressBar.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}