/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    AFloatButton: typeof import('ant-design-vue/es')['FloatButton']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    GGlobalLoading: typeof import('./src/components/GGlobalLoading/GGlobalLoading.vue')['default']
    GIcon: typeof import('./src/components/GIcon/GIcon.vue')['default']
    GPage: typeof import('./src/components/GPage/GPage.vue')['default']
    GProgressBar: typeof import('./src/components/GProgressBar/GProgressBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const AButton: typeof import('ant-design-vue/es')['Button']
  const ACard: typeof import('ant-design-vue/es')['Card']
  const ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
  const AFloatButton: typeof import('ant-design-vue/es')['FloatButton']
  const AForm: typeof import('ant-design-vue/es')['Form']
  const AFormItem: typeof import('ant-design-vue/es')['FormItem']
  const AInput: typeof import('ant-design-vue/es')['Input']
  const AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
  const GGlobalLoading: typeof import('./src/components/GGlobalLoading/GGlobalLoading.vue')['default']
  const GIcon: typeof import('./src/components/GIcon/GIcon.vue')['default']
  const GPage: typeof import('./src/components/GPage/GPage.vue')['default']
  const GProgressBar: typeof import('./src/components/GProgressBar/GProgressBar.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}